services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=ama
      - POSTGRES_PASSWORD=amabohachu
      - POSTGRES_DB=medparcour
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    user: "${UID}:${GID}"
    networks:
      - airflow

  webserver:
    image: apache/airflow:2.5.0
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://ama:amabohachu@postgres:5432/medparcour
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts/entrypoint.sh:/entrypoint.sh
      - ./logs:/opt/airflow/logs
    entrypoint: /entrypoint.sh
    ports:
      - "8080:8080"
    networks:
      - airflow

networks:
  airflow:

  